### ISSUE TITLE
關於生成的歌曲

### ISSUE THREAD

**Issue by maojui** [djosix/Performance-RNN-PyTorch#1]
沒很好聽。

**Comment by djosix** [comment]
你木耳啦！

**Comment by djosix** [comment]
Images for `README.md`

![sample-1](https://user-images.githubusercontent.com/17045050/42017017-337ce0a2-7ae0-11e8-8193-12ea539af424.png)

![sample-2](https://user-images.githubusercontent.com/17045050/42017026-37dfd7b2-7ae0-11e8-99a9-75d27510f44b.png)

![sample-piano-roll](https://user-images.githubusercontent.com/17045050/42017029-3b4f7060-7ae0-11e8-829b-6d6b8b829759.png)

**Comment by djosix** [comment]
Figure for `README.md`

![training-figure](https://user-images.githubusercontent.com/17045050/42135712-7f6e25f4-7d81-11e8-845f-682bd26a3abb.png)
