### ISSUE TITLE
Question regarding training and sample generation

### ISSUE THREAD

**Issue by axiom-of-joy** [djosix/Performance-RNN-PyTorch#3]
I have a few questions regarding training and sample generation:

1. Are the parameter values in `config.py` the values you used in producing your trained models?

2. For how many epochs did you train your model, and can you recall how long training took and using what hardware?

3. What values for greedy ratio, beam size, and temperature did you use to generate your musical samples?

Thanks for the clean and well-documented implementation!

**Comment by djosix** [comment]
1. Yes.
2. I forgot the actual number of epochs, but it took about 3 hours training on GTX 1080ti.
3. Those samples were not generated with beam search. Actually, I lost my `.bash_history`, so I'm not sure.

**Comment by axiom-of-joy** [comment]
Dear Yuankui,

Thanks very much for the info!

Best regards,
Xander Song
