### ISSUE TITLE
Question regarding -c flag for music generation

### ISSUE THREAD

**Issue by axiom-of-joy** [djosix/Performance-RNN-PyTorch#4]
This implementation supports generation using a control sequence, where the control sequence is a distribution on the notes to be played. For example,

```
python3 generate.py -s save/test.sess -l 1000 -c '1,0,1,0,1,1,0,1,0,1,0,1;3'
```
instructs the music generator to produce a response in C major. It's also possible to pass the `.data` file corresponding to a processed MIDI file with the `-c` flag, as in
```
python3 generate.py -s save/test.sess -c test.data
```
I am confused what this latter case is supposed to do. Does it calculate the distribution of pitches played in the MIDI file corresponding to `test.data` and use that as a control sequence?

**Comment by djosix** [comment]
Yes, it calculates pitch distribution and note density from test.data as a control sequence.

**Comment by axiom-of-joy** [comment]
Thanks.
