### ISSUE TITLE
Generate other scales besides C

### ISSUE THREAD

**Issue by Tetrix** [djosix/Performance-RNN-PyTorch#5]
I would like to know if there is an option to generate other scales besides C?
For example D Major and D Minor.

From the examples provided it is not clear to me how to produce other scales.

**Comment by djosix** [comment]
`-c` takes `C,C#,D,D#,E,F,F#,G,G#,A,A#,B;note_density`

For example:
- C Major Scale = `1,0,1,0,1,1,0,1,0,1,0,1` (C, D, E, F, G, A, B)
- D Major Scale = `0,1,1,0,1,0,1,1,0,1,0,1` (C#, D, E, F#, G, A, B)
- ...
